const list = [
    {
        id: 1,
        title:"Rich Dad Poor Dad",
        author:"Robert Kiyosaki",
        price:250,
        image: "../assests/imga.jpg",
        amount: 1,
    },
    {
        id: 2,
        title:"Rich Dad Poor Dad",
        author:"Robert Kiyosaki",
        price:250,
        image: "../assests/imga.jpg",
        amount: 2,
    },
    {
        id: 3,
        title:"Rich Dad Poor Dad",
        author:"Robert Kiyosaki",
        price:250,
        image: "../assests/imga.jpg",
        amount: 3,
    },
    {
        id: 4,
        title:"Rich Dad Poor Dad",
        author:"Robert Kiyosaki",
        price:250,
        image: "../assests/imga.jpg",
        amount: 4,
    },
    {
        id: 5,
        title:"Rich Dad Poor Dad",
        author:"Robert Kiyosaki",
        price:250,
        image: "../assests/imga.jpg",
        amount: 5,
    },
    {
        id: 6,
        title:"Rich Dad Poor Dad",
        author:"Robert Kiyosaki",
        price:250,
        image: "../assests/imga.jpg",
        amount: 6,
    },
    {
        id: 7,
        title:"Rich Dad Poor Dad",
        author:"Robert Kiyosaki",
        price:250,
        image: "../assests/imga.jpg",
        amount: 7,
    },
    {
        id: 8,
        title:"Rich Dad Poor Dad",
        author:"Robert Kiyosaki",
        price:250,
        image: "../assests/imga.jpg",
        amount: 8,
    },
    {
        id: 9,
        title:"Rich Dad Poor Dad",
        author:"Robert Kiyosaki",
        price:250,
        image: "../assests/imga.jpg",
        amount: 9,
    },
]

export default list;